import fs from "node:fs";
import path from "node:path";

/**
 * Company-target autocomplete pool (onboarding wizard + Settings):
 * reads the project's vetted Ashby/Lever/Greenhouse slug lists at
 * runtime (same fs.readFileSync + JSON.parse pattern resumes.ts
 * already uses for data/resumes/.resume_meta.json), so there's one
 * source of truth instead of a separately-maintained company list.
 * workday_tenants / simplify_feeds stay Settings/hand-edit only —
 * Workday has no company-slug API (a full tenant host/site path is
 * needed per company) and is review-only besides, so it's out of
 * scope for this autocomplete-driven flow. */

export interface CompanyEntry {
  slug: string;
  vendor: "ashby" | "lever" | "greenhouse";
  display: string;
  /** "vetted" = one of the hand-verified starter companies (see the
   *  config/*_vetted_slugs.json provenance notes); "discovered" = pulled
   *  in from a much larger external source and not individually
   *  hand-checked. Only "vetted" exists today — the tag is here so
   *  autocomplete.ts's weightOf hook has something real to rank on the
   *  moment a "discovered" tier is added, without another refactor. */
  tier: "vetted" | "discovered";
}

/** Vetted entries always outrank discovered ones on a search-score tie
 *  (or near-tie) — see autocomplete.ts's filterSuggestions `weightOf`
 *  parameter. Exported so callers don't hardcode the tier->weight
 *  mapping in more than one place. */
export function companyWeight(entry: CompanyEntry): number {
  return entry.tier === "vetted" ? 50 : 0;
}

interface VettedSlugsFile {
  slugs?: unknown;
}

function readSlugs(root: string, filename: string): string[] {
  try {
    const raw = fs.readFileSync(path.join(root, "config", filename), "utf8");
    const parsed = JSON.parse(raw) as VettedSlugsFile;
    if (!Array.isArray(parsed.slugs)) return [];
    return parsed.slugs.filter((s): s is string => typeof s === "string" && s.trim().length > 0);
  } catch {
    return [];
  }
}

interface DiscoveredCompaniesFile {
  companies?: unknown;
}

interface DiscoveredCompanyRecord {
  company_name: string;
  vendor: "ashby" | "lever" | "greenhouse";
  slug: string;
}

const KNOWN_VENDORS = new Set(["ashby", "lever", "greenhouse"]);

function isDiscoveredCompanyRecord(v: unknown): v is DiscoveredCompanyRecord {
  if (typeof v !== "object" || v === null) return false;
  const r = v as Record<string, unknown>;
  return (
    typeof r.company_name === "string" &&
    r.company_name.trim().length > 0 &&
    typeof r.vendor === "string" &&
    KNOWN_VENDORS.has(r.vendor) &&
    typeof r.slug === "string" &&
    r.slug.trim().length > 0
  );
}

/** Generated by scripts/validate/build_discovered_companies.py from
 *  SimplifyJobs' listing feeds — see that script's docstring for
 *  provenance/refresh details. Missing/malformed file just yields no
 *  discovered entries (the vetted lists alone still work). */
function readDiscoveredCompanies(root: string): DiscoveredCompanyRecord[] {
  try {
    const raw = fs.readFileSync(path.join(root, "config", "discovered_companies.json"), "utf8");
    const parsed = JSON.parse(raw) as DiscoveredCompaniesFile;
    if (!Array.isArray(parsed.companies)) return [];
    return parsed.companies.filter(isDiscoveredCompanyRecord);
  } catch {
    return [];
  }
}

/** Title-cases a slug ("elevenlabs" -> "Elevenlabs", "shield-ai" -> "Shield Ai")
 *  — a best-effort display name; there's no separate human-name source
 *  for these vetted lists today. */
function displayFromSlug(slug: string): string {
  return slug
    .split(/[-_]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export function loadCompanyDirectory(root: string): CompanyEntry[] {
  const ashby: CompanyEntry[] = readSlugs(root, "ashby_vetted_slugs.json").map((slug) => ({
    slug,
    vendor: "ashby",
    display: displayFromSlug(slug),
    tier: "vetted",
  }));
  const lever: CompanyEntry[] = readSlugs(root, "lever_vetted_slugs.json").map((slug) => ({
    slug,
    vendor: "lever",
    display: displayFromSlug(slug),
    tier: "vetted",
  }));
  const greenhouse: CompanyEntry[] = readSlugs(root, "greenhouse_vetted_slugs.json").map((slug) => ({
    slug,
    vendor: "greenhouse",
    display: displayFromSlug(slug),
    tier: "vetted",
  }));
  const vetted = [...ashby, ...lever, ...greenhouse];

  // A discovered record whose (vendor, slug) matches a hand-vetted one
  // is the same company — skip it rather than showing the name twice,
  // and let the hand-verified entry (and its display name) win.
  const vettedKeys = new Set(vetted.map((e) => `${e.vendor}:${e.slug}`));
  const discovered: CompanyEntry[] = readDiscoveredCompanies(root)
    .filter((r) => !vettedKeys.has(`${r.vendor}:${r.slug}`))
    .map((r) => ({
      slug: r.slug,
      vendor: r.vendor,
      display: r.company_name,
      tier: "discovered",
    }));

  return [...vetted, ...discovered].sort((a, b) => a.display.localeCompare(b.display));
}
